### ISSUE TITLE
Problems re-indexing

### ISSUE THREAD

**Issue by charlesreid1** [dcppc/centillion#151]
While re-indexing with 1.7.1:

can't find files in several repos (empty?):

```
INFO:root:Parsing file ids from repository dcppc/dcppc-deliverables
INFO:root:Parsing file ids from repository dcppc/dcppc-bot
ERROR:root:ERROR: could not get commits from repository dcppc/guids
Traceback (most recent call last):
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/centillion-1.7.1-py3.6.egg/centillion/search/__init__.py", line 1055, in update_index_ghfiles
    last = commits[0]
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/PaginatedList.py", line 55, in __getitem__
    self.__fetchToIndex(index)
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/PaginatedList.py", line 73, in __fetchToIndex
    self._grow()
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/PaginatedList.py", line 76, in _grow
    newElements = self._fetchNextPage()
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/PaginatedList.py", line 196, in _fetchNextPage
    headers=self.__headers
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/Requester.py", line 262, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/Requester.py", line 273, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 409 {'message': 'Git Repository is empty.', 'documentation_url': 'https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository'}
INFO:root:Parsing file ids from repository dcppc/dcppc.github.io
ERROR:root:ERROR: could not get commits from repository dcppc/test-dcppc-deliverables
Traceback (most recent call last):
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/centillion-1.7.1-py3.6.egg/centillion/search/__init__.py", line 1055, in update_index_ghfiles
    last = commits[0]
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/PaginatedList.py", line 55, in __getitem__
    self.__fetchToIndex(index)
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/PaginatedList.py", line 73, in __fetchToIndex
    self._grow()
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/PaginatedList.py", line 76, in _grow
    newElements = self._fetchNextPage()
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/PaginatedList.py", line 196, in _fetchNextPage
    headers=self.__headers
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/Requester.py", line 262, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/github/Requester.py", line 273, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.GithubException: 409 {'message': 'Git Repository is empty.', 'documentation_url': 'https://developer.github.com/v3/repos/commits/#list-commits-on-a-repository'}
INFO:root:Parsing file ids from repository dcppc/crosscut-metadata
INFO:root:Parsing file ids from repository dcppc/project-management
INFO:root:Parsing file ids from repository dcppc/dcppc-milestones
INFO:root:Parsing file ids from repository dcppc/dcppc-workshops
INFO:root:Parsing file ids from repository dcppc/2018-may-workshop
```

--------

then problems with github files:

```
INFO:root:Indexing github file update_calendars.sh from repo dcppc/calendars
INFO:root:Indexing markdown doc USERSTORY-45.md from repo dcppc/use-case-library
INFO:root:Indexing github file style.css from repo dcppc/dcppc.github.io
ERROR:root:ERROR: Failed to find file info.
Traceback (most recent call last):
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/centillion-1.7.1-py3.6.egg/centillion/search/__init__.py", line 554, in add_ghfile
    furl = d['url']
KeyError: 'url'
ERROR:root:dict_keys(['path', 'mode', 'type', 'sha', 'org', 'repo'])
INFO:root:Indexing github file gtex from repo dcppc/crosscut-metadata
```

later:

```
INFO:root:Indexing github file old from repo dcppc/dcppc-bot
INFO:root:Indexing markdown doc hooks.md from repo dcppc/uncle-archie
INFO:root:Indexing github file TEAM-Nitrogen-Ma'ayan.csv from repo dcppc/project-management
INFO:root:Indexing github file samples.py from repo dcppc/crosscut-metadata
ERROR:root:ERROR: Failed to find file info.
Traceback (most recent call last):
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/centillion-1.7.1-py3.6.egg/centillion/search/__init__.py", line 554, in add_ghfile
    furl = d['url']
KeyError: 'url'
```

later:

```
INFO:root:Indexing github file github_files.py from repo dcppc/crosscut-metadata
ERROR:root:ERROR: Failed to find file info.
Traceback (most recent call last):
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/centillion-1.7.1-py3.6.egg/centillion/search/__init__.py", line 554, in add_ghfile
    furl = d['url']
KeyError: 'url'
```

-------------------

also google drive pandoc problems, this error shows up multiple times:

```
INFO:root:Indexing Google Drive document "FAIR Rubrics and Assessments" of type document
INFO:root: > Extracting content
ERROR:root: > XXXXXX Failed to index Google Drive document "FAIR Rubrics and Assessments"
Traceback (most recent call last):
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/centillion-1.7.1-py3.6.egg/centillion/search/__init__.py", line 383, in add_drive_file
    outputfile=fullpath_output
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/pypandoc/__init__.py", line 140, in convert_file
    outputfile=outputfile, filters=filters)
  File "/home/ubuntu/centillion/vp/lib/python3.6/site-packages/pypandoc/__init__.py", line 325, in _convert_input
    'Pandoc died with exitcode "%s" during conversion: %s' % (p.returncode, stderr)
RuntimeError: Pandoc died with exitcode "1" during conversion: b"pandoc: couldn't parse docx file\nCallStack (from HasCallStack):\n  error, called at src/Text/Pandoc/Error.hs:55:28 in pandoc-1.19.2.4-HbfKWUyODESBIy0vGktOwX:Text.Pandoc.Error\n"
```

**Comment by charlesreid1** [comment]
fixed - see 1cbed8e0
